### signin Request
POST https://dkmh.onrender.com/api/v1/auth/login
Content-Type: application/json

{
    "email": "huynhduc.tai@hcmut.edu.vn",
    "password": "12345678"
}

###
GET https://dkmh.onrender.com/api/v1/user-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MjIxMjk3MSwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3MzM3MTI4NTIsImV4cCI6MTczMzcxNjQ1Mn0.5sXU-ywz2cnYTCQJNFJ3IvjpcTLdZlJrIijKHcYjWCE

###
PUT https://dkmh.onrender.com/api/v1/user-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MjIxMjM1Miwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3MzMyOTM0MTIsImV4cCI6MTczMzI5NzAxMn0.bN-K55BD48AQuDhKa6oB9KJ6uJVguquiriKSPpQ7Ask

{
    "email": "hothanhnhanhot@gmail.com",
    "dia_chi": "updateDTO.dia_chi",
    "sdt": "0976481171",
    "cccd": "054204003408",
    "ngay_sinh": "2004-06-11"
}

### lay tat ca dot dang ky
GET https://dkmh.onrender.com/api/v1/subject-registration
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MjIxMjM1Miwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3MzMyOTM0MTIsImV4cCI6MTczMzI5NzAxMn0.bN-K55BD48AQuDhKa6oB9KJ6uJVguquiriKSPpQ7Ask

### kiem tra ngay gio dang ky hop le cua sinh vien
GET https://dkmh.onrender.com/api/v1/subject-registration/checkvalidtimerange/DK_HK242_D2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MjIxMjM1Miwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3MzMyOTM0MTIsImV4cCI6MTczMzI5NzAxMn0.bN-K55BD48AQuDhKa6oB9KJ6uJVguquiriKSPpQ7Ask

### lay chi tiet lop hoc
GET https://dkmh.onrender.com/api/v1/subject-registration/search_subject/PH1003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MjIxMjM1Miwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3MzMyOTM0MTIsImV4cCI6MTczMzI5NzAxMn0.bN-K55BD48AQuDhKa6oB9KJ6uJVguquiriKSPpQ7Ask

### lay chi tiet lop hoc trong mon hoc trong 1 dot dang ky
GET https://dkmh.onrender.com/api/v1/subject-registration/class_details?ma_dot_dk=DK_HK233_D3&ma_hk=HK233&ma_mon=PH1003
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6MjIxMjM1Miwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3MzMyOTM0MTIsImV4cCI6MTczMzI5NzAxMn0.bN-K55BD48AQuDhKa6oB9KJ6uJVguquiriKSPpQ7Asks